name: SolisManagerBuild
on: 
  push:
  workflow_dispatch:
    inputs:
      git-ref:
        description: Git Ref (Optional)    
        required: false

jobs:
  build-solismanager:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [mac, linux, windows, raspi]
        include: 
          - target: windows
            os: ubuntu-latest
            runtime: win-x64
          - target: linux
            os: ubuntu-latest
            runtime: linux-x64
          - target: mac
            os: macos-latest
            runtime: osx-x64
          - target: raspi
            os: ubuntu-latest
            runtime: linux-arm64
     
    steps:
    - name: Clone Repository (release)
      uses: actions/checkout@v3

    - name: Clone Repository (Custom Ref)
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.git-ref }}
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4.2.0
      with:
        dotnet-version: 9.0.x

    - name: Install WASM-Tools
      run: dotnet workload install wasm-tools

    - name: Build SolisManager-${{matrix.target}}
      run: dotnet publish SolisManager/SolisManager.csproj -c Release --runtime ${{matrix.runtime}} --self-contained true -p:PublishTrimmed=false --property:PublishDir=${{github.workspace}}/publish /p:Version=1.0.${{github.run_number}}
    
    - name: Add Version File
      run: echo 1.0.${{github.run_number}} > ${{github.workspace}}/publish/version.txt
      
    - name: Zip the release
      run: |
           pushd ${{github.workspace}}/publish
           zip -r ${{github.workspace}}/publish/SolisManager-${{matrix.target}}.zip . 
           popd

    - name: Upload Dev artifacts
      if: github.ref == 'refs/heads/develop'
      uses: actions/upload-artifact@v4
      with:
        name: SolisManager-${{ matrix.target }}-1.0.${{ github.run_number }}-dev.zip
        path: ${{github.workspace}}/publish/SolisManager-${{matrix.target}}.zip
        retention-days: 5    

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v2
      with:
        files: ${{github.workspace}}/publish/SolisManager-${{matrix.target}}.zip
        name: Release 1.0.${{ github.run_number }}
        tag_name: 1.0.${{ github.run_number }}
        body: 'To install via docker: `docker pull webreaper/solisagilemanager:1.0.${{ github.run_number }}`'
        make_latest: true

  build-docker:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix: 
        target: [linux]
        include: 
          - target: linux
            os: ubuntu-latest
            platform: linux/amd64
            docker-platforms: linux/arm64, linux/amd64, darwin, linux/arm, linux/arm/v7, linux/arm/v6, linux/arm/v5

    steps:        
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ matrix.docker-platforms }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
      - name: Build/push develop
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v6
        with:
          push: true
          build-args: VERSION=1.0.${{ github.run_number }}-dev
          platforms: ${{matrix.docker-platforms}}
          tags: webreaper/solisagilemanager:dev
          
      - name: Build/push release
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: VERSION=1.0.${{ github.run_number }}
          platforms: ${{matrix.docker-platforms}}
          tags: webreaper/solisagilemanager:1.0.${{ github.run_number }}, webreaper/solisagilemanager:latest
